<?php

$_txtr['client']['makeAdmin'][0]              = 'Zum Admin ernennen';
$_txtr['client']['makeAdmin'][1]              = 'Adminrechte entziehen';

$_txtr['client']['sendNewPassword']           = 'Neues Password versendet';
$_txtr['client']['sendNewPasswordfail']       = 'Beim Versenden der Mail ist ein Fehler aufgetreten.';

$_txtr['user']['notActivated']                = 'Dieser Account wurde nocht nicht aktiviert.';

$_txtr['newPasswordMail']['subject']          = 'Dein neues Passwort';

$_txtr['Mailererror']['noRecipient']          = 'Mailversand nicht möglich. Kein Empfänger gesetzt.';
$_txtr['Mailererror']['noSubject']            = 'Mailversand nicht möglich. Kein Betreff gesetzt.';

$_txtr['api']['noMethodSet']                  = 'no method set. aborting.';
$_txtr['api']['noActionSet']                  = 'no action set. aborting.';
